### PR TITLE
Add .editorconfig

### PR DESCRIPTION
**Pull request by rvost**
Add some important files missing from `rewrite`:

* `.gitignore`;
* `.gitattributes`
  Added for consistency;
* `.editorconfig`
   This helps to ensure a consistent coding style throughout the project, regardless of the development environment and editor preferences used. Configuration is pretty standard for .NET projects, feel free to tweak it to suit your preferences.

## Considerations

* The current code style does not use curly braces when the `if` or loop body is a single statement. However, C# most commonly uses curly braces (and puts them on a new line), and this is reflected in the `.editorconfig` file. You may want to change the ruleset or style of existing code.
* I didn't clean up the code based on the new `.editorconfig` to avoid potential merge conflicts, but I can add it to the PR before the merge if you like.

### CODE REVIEW

**Comment by FlipperPlz** [comment]
LGTM, is this ready to merge?

**Comment by rvost** [comment]
If you agree with the proposed rule set, yes.

**Comment by rvost** [comment]
Fine

**Comment by rvost** [comment]
Then it's ready to merge

**Comment by FlipperPlz** [comment]
Thanks again for the help!

**Pull request merged**
