### PR TITLE
BisUtils Total Project Rewrite

### PR DESCRIPTION
**Pull request by FlipperPlz**
The proposed pull request stems from the need to refactor and rewrite a significant portion of the codebase for this project. The initial implementation, despite its functional state, was rough around the edges. It was characterized by an alarming amount of coding practices that promoted technical debt, impairing future enhancements and maintenance.
Some of the preceding deterrents that necessitated this drastic action included code duplication, poor error handling amongst others. There was a considerable lack of consistency in coding style, which made the project hard to read and comprehend. A particular issue was a weak logical separation of concerns. Modules were tightly coupled, and there was a minimal degree of modularity.
The updated codebase in the pull request is a concerted effort to clean up the original implementation. It prioritizes enhancing readability, maintainability, and extensibility. Key focuses of the rewrite include proper encapsulation, abstraction, and separation of concerns.
By using code structures aligning with the SOLID design principles, it was possible to create clear, modular sections of functionality which can now be more easily tested, debugged, and expanded. Moreover, extensive comments have been added to improve understanding and provide context on how the code works, facilitating any future work or updates.
The refactored project does not diminish the current project's capabilities. Instead, it has significantly improved code quality, paving the way for easier maintenance and paving the way for new features informed by best coding practices.

### CODE REVIEW

**Review by rvost — COMMENTED** [review]
I'm sorry, but I don't understand the benefit of such a merger. Since there is no special meaning to branch names in git, and any branch can be set as the default on Github, you can simply rename `rewrite` to `master` (or `main`), and rename the branch currently called `master` to something like `leagcy`. This way, you can keep the `legacy` branch for users, as not all functionality (e.g. PAK handling) is implemented in `rewrite` yet.

**Comment by FlipperPlz** [comment]
This PR is only a draft as of now. Master will be pushed to a new branch called legacy before this PR is merged. When this PR is merged everything will be implemented.

**Comment by rvost** [comment]
Sounds reasonable

**Comment by FlipperPlz** [comment]
As with the current progression on the rewrite, a stable version of the library with all features implemented should be out within the month. Currently I'm targeting July 29th as a release date. As of today I have started to create a library for reading p3ds, but a few things need to be done first. I want to look over BisUtils.PBO and fix a view things that I feel are implemented poorly. I feel like the preprocessor is in a good state for release right now even though it only supports a handful of directives. I also want to get a proper system going for recognizing the current line in both normal lexers aswell as lexers that may have been preprocessed. As with the ParamFile library all that's left to finish is enums and binarization which is nearly done already.

**Pull request merged**
